### ISSUE TITLE
Failed: LoadLibrary

### ISSUE THREAD

**Issue by lodeslive** [AHK-just-me/Class_SQLiteDB#6]
i have been unable to even simply start the script
the error occurs when i attempt to use a '#Include Class_SQLiteDB.ahk' function (but not before)

the source of the error appears in Class_SQLiteDB.ahk in the function "__New()", when this code runs

`
        If !(DLL := DllCall("LoadLibrary", "Str", This.Base._SQLiteDLL, "UPtr")) {
            MsgBox, 16, SQLiteDB Error, % "DLL " . SQLiteDLL . " does not exist!"
            ExitApp
`

the msg of the error says the file does not exist, but I checked and it has no problem finding the file.
as I dont understand much about "DllCall", I cant say any more than "LoadLibrary" returns a false

I am using the latest version of SQLite.dll (Version: 3.35.1.0)
latest version of Class_SQLiteDB  (Version: 0.0.01.00)
Win 10

is it a problem with the Dll file version? i am having trouble getting my hands on sql3 oldVersions files, but i tried a few others and didnt work

what do u guys think would be the cause?

Note: 
I installed the most recent version of sqliteodbc (Version: 0.9998) but that had no effect.

**Comment by lodeslive** [comment]
[Solved]
i noticed the "Tested on: Win10 Pro(x64), SQLite 3.7.13" in "Class_SQLiteDB.ahk"
so i tried running it in 64bit (SQLite3.dll)
and that worked

does that mean that only 64bit works?
kinda odd ive not seen that mentioned anywhere.

**Comment by lodeslive** [comment]
[Solved]
i noticed the "Tested on: Win10 Pro(x64), SQLite 3.7.13" in "Class_SQLiteDB.ahk"
so i tried running it in 64bit (SQLite3.dll)
and that worked

does that mean that only 64bit works?
kinda odd ive not seen that mentioned anywhere.

**Comment by tamo** [comment]
SQLite3.dll has to have the same bitness of that of AutoHotkey.
Today I saw the same (or opposite) problem as yours.
I had installed AutoHotkeyU32 and the 64bit version of SQLite3.dll. Then Class_SQLiteDB said "SQLite3.dll does not exist!"
Re-installing the 32bit DLL wiped the problem.

So, 
```
If !(DLL := DllCall("LoadLibrary", "Str", This.Base._SQLiteDLL, "UPtr")) {
  MsgBox, 16, SQLiteDB Error, % "DLL " . SQLiteDLL . " does not exist!"
  ExitApp
}
```
should be something like this
```
If !(DLL := DllCall("LoadLibrary", "Str", This.Base._SQLiteDLL, "UPtr")) {
  If (FileExist(SQLiteDLL)) {
    AnotherBitness := (A_PtrSize = 4) ? "64" : "32"
    MsgBox, 16, SQLiteDB Error, % "DLL " . SQLiteDLL . " cannot be loaded! Maybe you should replace it with " . AnotherBitness . "bit version."
    ExitApp
  }
  MsgBox, 16, SQLiteDB Error, % "DLL " . SQLiteDLL . " does not exist!"
  ExitApp
}
```

It is not good to report "it does not exist" without actually examining FileExist(it).
